### ISSUE TITLE
Can't connect to decompiler!

### ISSUE THREAD

**Issue by BabyBroder** [mahaloz/decomp2dbg#105]
![image](https://github.com/user-attachments/assets/7ef95be6-08e1-40c4-b159-795b8641018b)

There are some problems when I connect to IDA, how can I fix it?

**Comment by mahaloz** [comment]
Hi, can you provide any more information? Did you start the server on IDA? What was the version of IDA and d2d?

**Comment by BabyBroder** [comment]
I have the problem when connect to IDA from WSL; however, I fix it successfully, thanks you!

**Comment by wccomuoi** [comment]
> I have the problem when connect to IDA from WSL; however, I fix it successfully, thanks you!

I'm having the same problem, how do you fix it?

**Comment by BabyBroder** [comment]
Well, I use the ip address of WSl instead of localhost, you can find it by command `ipconfig` in PS.

**Comment by wccomuoi** [comment]
Oh nvm it worked. Just setting the WSL ip in both decompiler and gdb
