### ISSUE TITLE
binary ninja plugin manager?

### ISSUE THREAD

**Issue by psifertex** [mahaloz/decomp2dbg#50]
The binary ninja plugin manager supports plugins that exist in subfolders. All it would take would be to [tag and cut a release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) (or using [release_helper](https://github.com/Vector35/release_helper)) and let me know on this issue and I can add it. Then subsequent releases automatically notify us and we update the plugin manager accordingly.

Note that I haven't looked at the current import hierarchy but because the plugin manager doesn't necessarily install things to the global namespace it might require some tweaks to how imports are done.

**Comment by mahaloz** [comment]
@psifertex I would love to add it to BN plugin manager... as you know, I have been dragging my feet on integration, though. The main problem I see (or think I see) is that decomp2dbg needs to install in Python to work, not just use its plugin files. 

As for the import system, it should be fine :tm:. If you let me know what to change to get it ready for integration, I would be happy to make it happen. 

Tag [v3.0.0](https://github.com/mahaloz/decomp2dbg/tree/v3.0.0) and Release [v3.0.0](https://github.com/mahaloz/decomp2dbg/releases/tag/v3.0.0) would work great for this.

**Comment by mahaloz** [comment]
@psifertex, we are ready to go! Release [v3.3.0](https://github.com/mahaloz/decomp2dbg/releases/tag/v3.3.0) and Tag [v3.3.0](https://github.com/mahaloz/decomp2dbg/tree/v3.3.0) are the versions ready for shipping into the plugin manager. And just to be specific, the binja plugin code can be found in the subdir here: 
https://github.com/mahaloz/decomp2dbg/tree/main/decompilers/d2d_binja

**Comment by psifertex** [comment]
Sounds great, thanks! Added it yesterday and it looks like it's installable (though there's another error I'll file separately).
