### ISSUE TITLE
deprecation warning on plus with QKeySequence

### ISSUE THREAD

**Issue by psifertex** [mahaloz/decomp2dbg#57]
It looks like there's been a deprecation in PySide 6 and the BN plugin:
```
/Users/jordan/Library/Application Support/Binary Ninja/repositories/community/plugins/mahaloz_decomp2dbg/decompilers/d2d_binja/d2d_binja.py:135: PySideDeprecationWarningRemovedInQt6: 
The "+" operator is deprecated in Qt For Python 6.0 .
Please use "|" instead.
  UIAction.registerAction(configure_d2d_id, QKeySequence(Qt.CTRL + Qt.SHIFT + Qt.Key_D))
```
https://github.com/mahaloz/decomp2dbg/blob/main/decompilers/d2d_binja/d2d_binja.py#L135

Looks like there's more info at: 
https://doc.qt.io/qt-6/qkeysequence.html#details

but the obvious fix looks straight-forward. Happy to submit a PR, but didn't know if there was reason to keep that pattern around  for some reason.

**Comment by mahaloz** [comment]
@psifertex fixed! I've bumped the latest version to 3.3.1 for this fix.
