### ISSUE TITLE
Decomp2dbg doesn't work when using an existing BinaryNinja database

### ISSUE THREAD

**Issue by owah** [mahaloz/decomp2dbg#61]
I noticed that when I try to continue with saved work, thus from a BNDB, decomp2dbg won't show the decompiler view, nor do the memory addresses reflect the proper names + offset in the assembly view. Maybe this is related to it being a PIE binary? (related to  https://github.com/mahaloz/decomp2dbg/issues/60 ?)

**Comment by mahaloz** [comment]
@owah can I assume you are doing this the same way as #60 ? Where you rebased the addresses in Binja, then started debugging?

**Comment by owah** [comment]
I have created a new bndb of two executables without rebasing anything, and then it loads fine.

**Comment by mahaloz** [comment]
Alright, I'm closing this since the base cause seems to be the same as #60.
