### ISSUE TITLE
Ghidra global variable not exported

### ISSUE THREAD

**Issue by Dvorhack** [mahaloz/decomp2dbg#63]
I'm using Ghidra and pwndbg and I don't get my ghidra global variables in .bss in gdb
But I do have the .data global variables in gdb

**Comment by mahaloz** [comment]
Interesting, would you happen to have a binary I can test this on?

**Comment by Dvorhack** [comment]
Still the same problem, and with the newer version event the variables in .data aren't exported

**Comment by mahaloz** [comment]
Hey @Dvorhack thanks for the patience. I believe I have fixed this in #72. I tested it on the binary your provided in the discord, attached here. I checked to see if it worked with `DAT_001050e8`, which is in the `.bss`. 

Binary is 
[vm.zip](https://github.com/mahaloz/decomp2dbg/files/11716026/vm.zip)
attached for reference.
