### ISSUE TITLE
Gradle does not produce the Ghidra extension

### ISSUE THREAD

**Issue by IridiumXOR** [mahaloz/decomp2dbg#78]
Hi,
I have tried to compile the D2D Ghidra extension for Ghidra 10.4 but gradle does not produce the zip containing the extension.
I have used Gradle 8.1.1 with command ```gradle -PGHIDRA_INSTALL_DIR=<MY GHIDRA SOURCE PATH> build```

**Comment by mahaloz** [comment]
Hi @IridiumXOR, are you attempting to do this inside Eclipse? I've only ever worked with the code in Eclipse, with the supported GhidraDev plugin.

**Comment by IridiumXOR** [comment]
No, directly from the extension directory. It seems to compile the extension but after it no ZIP archive. [Here](https://fossies.org/linux/ghidra/Ghidra/Extensions/bundle_examples/build.gradle) there is an example of gradle build system that permit to create a ZIP file for the extension. Maybe the problem is that decomp2dbg script does not have the "last" part of the example script which produce the ZIP

**Comment by mahaloz** [comment]
Just checked our CI, which is still passing, and we built like this:
https://github.com/mahaloz/decomp2dbg/blob/bca07ff4771caa34faa3f238afcf6b796928d370/.github/workflows/ghidra-build.yml#L47

You can also check the action logs to see the expanded command. It still builds, so I'm unsure how to provide support here.

**Comment by IridiumXOR** [comment]
Oh! I have discovered the problem! Sorry it's my fault! the ```build``` argument is NOT necessary! If I add it, it builds the extension but does not create the zip file! I suggest you to add a line in the README.md of d2d extension on how to compile it 
```gradle -PGHIDRA_INSTALL_DIR=<YOUR GHIDRA INSTALL DIR>```
Sorry again
