### ISSUE TITLE
ghidra 10.3.2 throw error when changing name during execution 

### ISSUE THREAD

**Issue by antkss** [mahaloz/decomp2dbg#96]
https://github.com/mahaloz/decomp2dbg/assets/88892713/3de84777-aee2-4de9-bece-74e43ac30275

**Comment by mahaloz** [comment]
@antkss thanks for the video. Any chance you can post the binary for easier testing?

**Comment by antkss** [comment]
> @antkss thanks for the video. Any chance you can post the binary for easier testing?
ok, here,  thank for your response
[heap.zip](https://github.com/mahaloz/decomp2dbg/files/15256583/heap.zip)

**Comment by mahaloz** [comment]
Fixed in `v3.9.1`, please reinstall `pip3 install -U decomp2dbg && decomp2dbg --install`.
